### ISSUE TITLE
New FAQs or fixbug with dashes endpoints

### ISSUE THREAD

**Issue by tanrax** [derlin/mantelo#14]
When we need to call to endpoint with "-" (dashes).

For example: 

```
/admin/realms/{realm}/client-scopes/
```

Is ...?

```python
connection.clients_scopes.post({'name': 'app-scope'})
```

Or

```python
connection.clients-scopes.post({'name': 'app-scope'})
```

Or... etc

Thanks in advance! 😁

**Comment by derlin** [comment]
Hello there! And thank you for reaching out.

This case is properly covered, I just haven't thought of documenting it. Let me add something in the "Making calls" section of the docs. Thank you for pointing it out! (I may also add something about the `.url()` method, which is handy in such cases).

As per your question: since in python dashes in properties are not allowed, mantelo automatically converts underscores to dashes. Thus, the correct mantelo way would be:
```python
# nice python way
connection.client_scopes.get()

# also doable (BUT DON'T ^^)
connection("client-scopes").get()
```

Note that if you have a doubt, you can use the following to get the exact URL without actually doing the call:
```python
connection.client_scopes.url()
# => 'http://localhost:9090/admin/realms/master/client-scopes'
```

**Comment by tanrax** [comment]
Thank you so much, you are the best.
Note: Your project is making my job easier.
You can close the issue whenever you want.
