### ISSUE TITLE
Bug when passing body to Delete

### ISSUE THREAD

**Issue by tanrax** [derlin/mantelo#17]
For example

```python
connection.users("boo").role_mappings.clients("foo").delete([{'id': "moo"}])
```

Output

```bash
TypeError: Resource.delete() takes 1 positional argument but 2 were given
```

I am using `DELETE /admin/realms/{realm}/users/{user-id}/role-mappings/clients/{client-id}` endpoint

**Comment by derlin** [comment]
Hello again @tanrax !

Gosh, Keycloak API is weirdly coded:

> The DELETE method has no defined semantics for the message body, so this should be empty. [source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE)

This issue has been [reported in slumber](https://github.com/samgiles/slumber/issues/150), but it has been open since 2019. I get that the slumber developers didn't support that in their first implementation, as it is not part of the HTTP protocol.

Given the low activity on slumber right now, I will try to fix it in mantelo itself. Just give me some time to implement it.

**Comment by tanrax** [comment]
> Given the low activity on slumber right now, I will try to fix it in mantelo itself. Just give me some time to implement it.

I don’t know how I can help you. You can talk with me about anything. Thank you, again :)

**Comment by derlin** [comment]
Hello @tanrax ! Just to let you know I didn't forget you!

I am working on eliminating slumber (and reimplementing it in Mantelo), as it has been inactive since 2018. I am at the final touches. Once done, your fix will be easy-peasy. There will also be some nice new features and documentation.

No promise, but I should be able to craft a 3.0.0 release within a week or so.

Happy Christmas!

**Comment by tanrax** [comment]
Hi @derlin !! From the little interaction we have had, I think you are a committed and hard-working person. I'm sure you are working hard. Your project is becoming one of my favorites.
Thank you very much for your incredible work.
Merry Christmas!!

**Comment by tanrax** [comment]
Congratulation on [v2.2.0 release](https://github.com/derlin/mantelo/releases/tag/v2.2.0) . Good job!
